{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE OverloadedLabels  #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeOperators     #-}

module Entity.Internal.Diary where

import           Control.Lens
import           Data.Extensible
import           Data.Text
import           Data.Time       ( UTCTime )

type Diary
   = Record '[ "title" >: Text, "content" >: Text, "imageUrls" >: [Text], "allowAutoEdit" >: Bool, "createdAt" >: UTCTime, "updatedAt" >: UTCTime]

type DiaryId = Int

type DiaryRecord = (DiaryId, Diary)

diary1 :: Diary
diary1 =
  #title @= "AutoDiary" <: #content @=
  "This is the first diary which is generated by Apricot. Images may be included in the diary as well." <:
  #imageUrls @=
  ["https://upload.wikimedia.org/wikipedia/commons/c/c4/Apricot_fruit.jpg"] <:
  #allowAutoEdit @=
  True <:
  #createdAt @=
  (read "2019-11-11 11:11:11" :: UTCTime) <:
  #updatedAt @=
  (read "2019-11-11 11:11:11" :: UTCTime) <:
  emptyRecord

diary1Id :: DiaryId
diary1Id = 1

diary1Record :: DiaryRecord
diary1Record = (diary1Id, diary1)
