--
-- PostgreSQL database dump
--

-- Dumped from database version 11.5
-- Dumped by pg_dump version 11.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: post; Type: TABLE; Schema: public; Owner: seb-user
--

CREATE TABLE public.post (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    title character varying NOT NULL,
    content character varying NOT NULL,
    allow_auto_edit boolean NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.post OWNER TO "seb-user";

--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: seb-user
--

CREATE SEQUENCE public.post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.post_id_seq OWNER TO "seb-user";

--
-- Name: post_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: seb-user
--

ALTER SEQUENCE public.post_id_seq OWNED BY public.post.id;


--
-- Name: post_image; Type: TABLE; Schema: public; Owner: seb-user
--

CREATE TABLE public.post_image (
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    url character varying NOT NULL
);


ALTER TABLE public.post_image OWNER TO "seb-user";

--
-- Name: post_image_id_seq; Type: SEQUENCE; Schema: public; Owner: seb-user
--

CREATE SEQUENCE public.post_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.post_image_id_seq OWNER TO "seb-user";

--
-- Name: post_image_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: seb-user
--

ALTER SEQUENCE public.post_image_id_seq OWNED BY public.post_image.id;


--
-- Name: user; Type: TABLE; Schema: public; Owner: seb-user
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    name character varying NOT NULL,
    email character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."user" OWNER TO "seb-user";

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: seb-user
--

CREATE SEQUENCE public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.user_id_seq OWNER TO "seb-user";

--
-- Name: user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: seb-user
--

ALTER SEQUENCE public.user_id_seq OWNED BY public."user".id;


--
-- Name: post id; Type: DEFAULT; Schema: public; Owner: seb-user
--

ALTER TABLE ONLY public.post ALTER COLUMN id SET DEFAULT nextval('public.post_id_seq'::regclass);


--
-- Name: post_image id; Type: DEFAULT; Schema: public; Owner: seb-user
--

ALTER TABLE ONLY public.post_image ALTER COLUMN id SET DEFAULT nextval('public.post_image_id_seq'::regclass);


--
-- Name: user id; Type: DEFAULT; Schema: public; Owner: seb-user
--

ALTER TABLE ONLY public."user" ALTER COLUMN id SET DEFAULT nextval('public.user_id_seq'::regclass);


--
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: seb-user
--

COPY public.post (id, user_id, title, content, allow_auto_edit, created_at, updated_at) FROM stdin;
1	1	AutoPost	This is the first post which is generated by Apricot. Images may be included in it as well.	t	2019-11-11 20:11:11+09	2019-11-11 20:11:11+09
2	2	Define your personal mission in life!	The key insights from The 7 Habits of Highly Effective People:\n1. Sharpen the saw\n2. Be proactive\n3. Begin with an end in mind\n4. Pu first things first\n5. Think win-win\n6. Seek first to understand, then to be understood\n7. Synergize\n	t	2019-11-11 20:11:11+09	2019-11-11 20:11:11+09
\.


--
-- Data for Name: post_image; Type: TABLE DATA; Schema: public; Owner: seb-user
--

COPY public.post_image (id, post_id, url) FROM stdin;
1	1	https://upload.wikimedia.org/wikipedia/commons/c/c4/Apricot_fruit.jpg
2	1	https://bedemco.com/bdc/wp-content/uploads/2017/12/shutterstock_178969106-1-1-570x385.jpg
3	2	https://m.media-amazon.com/images/I/51OuvCFwyZL._SL500_.jpg
4	2	https://archive.sltrib.com/images/2012/0717/biz_obit-covey_071712~2.jpg
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: seb-user
--

COPY public."user" (id, name, email, created_at) FROM stdin;
1	Neo	neo@matrix.mov	1999-09-11 09:00:00+09
2	Morpheus	morpheus@matrix.mov	1812-09-11 09:18:59+09:18:59
3	Trinity	trinity@matrix.mov	1995-12-31 21:13:14+09
\.


--
-- Name: post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: seb-user
--

SELECT pg_catalog.setval('public.post_id_seq', 2, true);


--
-- Name: post_image_id_seq; Type: SEQUENCE SET; Schema: public; Owner: seb-user
--

SELECT pg_catalog.setval('public.post_image_id_seq', 4, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: seb-user
--

SELECT pg_catalog.setval('public.user_id_seq', 3, true);


--
-- Name: post_image post_image_pkey; Type: CONSTRAINT; Schema: public; Owner: seb-user
--

ALTER TABLE ONLY public.post_image
    ADD CONSTRAINT post_image_pkey PRIMARY KEY (id);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: seb-user
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- Name: user unique_email; Type: CONSTRAINT; Schema: public; Owner: seb-user
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT unique_email UNIQUE (email);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: seb-user
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: post_image post_image_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: seb-user
--

ALTER TABLE ONLY public.post_image
    ADD CONSTRAINT post_image_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: post post_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: seb-user
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- PostgreSQL database dump complete
--

